// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_HF_w5j0KOB-BrC0MklAmMg5yTXyKII',
    appId: '1:913727559148:web:f3c8cbcc19395ed4ba9cc9',
    messagingSenderId: '913727559148',
    projectId: 'gerena-de29f',
    authDomain: 'gerena-de29f.firebaseapp.com',
    storageBucket: 'gerena-de29f.firebasestorage.app',
    measurementId: 'G-2DDR9J8GY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA04X84ZycQ9e9ZLHSi4w-rIqkgJsoOYF4',
    appId: '1:913727559148:android:d36524d3d54ddbdbba9cc9',
    messagingSenderId: '913727559148',
    projectId: 'gerena-de29f',
    storageBucket: 'gerena-de29f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDnxZAAV6nxGHghdaP_tbi8cIt5AC3zE',
    appId: '1:913727559148:ios:56a75b797283f578ba9cc9',
    messagingSenderId: '913727559148',
    projectId: 'gerena-de29f',
    storageBucket: 'gerena-de29f.firebasestorage.app',
    iosBundleId: 'dev.binteconsulting.gerena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeDnxZAAV6nxGHghdaP_tbi8cIt5AC3zE',
    appId: '1:913727559148:ios:56a75b797283f578ba9cc9',
    messagingSenderId: '913727559148',
    projectId: 'gerena-de29f',
    storageBucket: 'gerena-de29f.firebasestorage.app',
    iosBundleId: 'dev.binteconsulting.gerena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz_HF_w5j0KOB-BrC0MklAmMg5yTXyKII',
    appId: '1:913727559148:web:ff428078a738d9b5ba9cc9',
    messagingSenderId: '913727559148',
    projectId: 'gerena-de29f',
    authDomain: 'gerena-de29f.firebaseapp.com',
    storageBucket: 'gerena-de29f.firebasestorage.app',
    measurementId: 'G-KDSZJFWVT4',
  );
}
